### ISSUE TITLE
1.20.1 has Continuity as a hard dependency

### ISSUE THREAD

**Issue by Sombrand** [matthewperiut/Chisel-Reborn#34]
Chisel Reborn 1.20.1 for Fabric has Continuity as a hard dependency for loading. However, Continuity is a client-side mod, and so it hasn’t been approved for servers (and likely won’t be). I have Continuity client-side so it won’t be an issue regarding not having it at all, but the server won’t load without it being server-side too.

Here's the log for the server not loading, if it helps:

[14:11:54] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.15.3 [14:11:54] [main/WARN]: Mod resolution failed [14:11:54] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE chisel 1.6 {depends continuity @ []}, ROOT_FORCELOAD_SINGLE chisel 1.6] [14:11:54] [main/INFO]: Reason: [HARD_DEP chisel 1.6 {depends continuity @ []}] [14:11:54] [main/INFO]: SERVER environment disabled: [fabric-model-loading-api-v1, fabric-renderer-api-v1, fabric-keybindings-v0, fabric-renderer-registries-v1, fabric-models-v0, fabric-client-tags-api-v1, fabric-rendering-v0, fabric-screen-api-v1, fabric-sound-api-v1, fabric-rendering-v1, fabric-key-binding-api-v1, fabric-renderer-indigo, fabric-blockrenderlayer-v1] [14:11:54] [main/INFO]: Fix: add [add:continuity 1 ([(-∞,∞)])], remove [], replace [] [14:11:54] [main/ERROR]: Incompatible mods found! net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other! A potential solution has been determined, this may resolve your problem: - Install continuity, any version. More details: - Mod 'Chisel Reborn' (chisel) 1.6 requires any version of continuity, which is missing! at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.15.3.jar:?] at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195) ~[fabric-loader-0.15.3.jar:?] at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.15.3.jar:?] at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.15.3.jar:?] at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.3.jar:?] at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.3.jar:?]

**Comment by matthewperiut** [comment]
Removed as hard dependency! sorry about that
