### ISSUE TITLE
[1.21] Fabric 1.8.1 - Crash  java.lang.IllegalStateException: Value must be within range [1;99]: 0; Item must not be minecraft:air

### ISSUE THREAD

**Issue by joaquinlarroca** [matthewperiut/Chisel-Reborn#44]
The game crashed after i left an item inside the chisel and when i opened it this error poped up "The game crashed whilst saving entity nbt
Error: java.lang.IllegalStateException: Value must be within range [1;99]: 0; Item must not be minecraft:air"

`---- Minecraft Crash Report ----
// There are four lights!

Time: 2024-07-07 14:12:19
Description: Saving entity NBT

java.lang.IllegalStateException: Value must be within range [1;99]: 0; Item must not be minecraft:air
	at com.mojang.serialization.DataResult$Error.getOrThrow(DataResult.java:287)
	at com.mojang.serialization.DataResult.getOrThrow(DataResult.java:81)
	at net.minecraft.class_1799.method_57376(class_1799.java:396)
	at net.minecraft.class_1661.method_7384(class_1661.java:408)
	at net.minecraft.class_1657.method_5652(class_1657.java:895)
	at net.minecraft.class_3222.method_5652(class_3222.java:412)
	at net.minecraft.class_1297.method_5647(class_1297.java:1922)
	at net.minecraft.class_2105.method_9076(class_2105.java:39)
	at net.minecraft.class_2105.method_9072(class_2105.java:31)
	at net.minecraft.class_2048.method_8909(class_2048.java:189)
	at net.minecraft.class_215.method_914(class_215.java:39)
	at net.minecraft.class_215.test(class_215.java:16)
	at net.minecraft.class_207.method_888(class_207.java:23)
	at net.minecraft.class_207.test(class_207.java:11)
	at net.minecraft.class_156.method_56617(class_156.java:334)
	at net.minecraft.class_5258.method_27806(class_5258.java:29)
	at net.minecraft.class_4558.method_22510(class_4558.java:61)
	at net.minecraft.class_2135.method_9141(class_2135.java:22)
	at net.minecraft.class_3222.method_5773(class_3222.java:554)
	at net.minecraft.class_3218.method_18762(class_3218.java:770)
	at net.minecraft.class_1937.method_18472(class_1937.java:498)
	at net.minecraft.class_3218.method_31420(class_3218.java:408)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:372)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at net.minecraft.class_1132.method_3748(class_1132.java:114)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------`

**Comment by joaquinlarroca** [comment]
The solution was to throw the chisel into lava

**Comment by matthewperiut** [comment]
did you upgrade from chisel 1.20 to 1.21?

**Comment by joaquinlarroca** [comment]
no i just installed the 1.21 version, i didnt used it befor

**Comment by matthewperiut** [comment]
Hmm is there anything you did to the chisel before this happened?

**Comment by matthewperiut** [comment]
Actually what item did you leave in the chisel

**Comment by joaquinlarroca** [comment]
I think it was cobbled deepslate

**Comment by matthewperiut** [comment]
This turned out to be a minecraft bug.
